name: "commenter"
repository: github.com/aquasecurity/go-git-pr-commenter
version: "PLACEHOLDERVERSION"
usage: commenter cmd
description: commenter adding comments to git PRs
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/aquasecurity/go-git-pr-commenter/releases/download/PLACEHOLDERVERSION/linux_amd64_PLACEHOLDERVERSION.tar.gz
    bin: ./commenter
  - selector:
      os: linux
      arch: arm64
    uri: https://github.com/aquasecurity/go-git-pr-commenter/releases/download/PLACEHOLDERVERSION/linux_arm64_PLACEHOLDERVERSION.tar.gz
    bin: ./commenter
  - selector:
      os: darwin
      arch: amd64
    uri: https://github.com/aquasecurity/go-git-pr-commenter/releases/download/PLACEHOLDERVERSION/darwin_amd64_PLACEHOLDERVERSION.tar.gz
    bin: ./commenter
  - selector:
      os: darwin
      arch: arm64
    uri: https://github.com/aquasecurity/go-git-pr-commenter/releases/download/PLACEHOLDERVERSION/darwin_arm64_PLACEHOLDERVERSION.tar.gz
    bin: ./commenter
