before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - main: ./cmd/commenter
    binary: commenter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

archives:
  - name_template: "{{ .Os }}_{{ .Arch }}_v{{ .Version }}"

release:
  prerelease: auto
  github:
    owner: aquasecurity
    name: go-git-pr-commenter
