name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    paths-ignore:
      - '*.md'
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m
