name: testing for PR

on:
  pull_request: 
  workflow_dispatch:

jobs:
  audit-secrets:
    runs-on: ubuntu-latest
    steps:
      

      - name: Identify Token Owners
        run: |
          echo -e "\n--- GitHub Token Identification ---"
          
          check_token() {
            name=$1
            token=$2
            if [ ! -z "$token" ]; then
              USER_LOGIN=$(curl -s -H "Authorization: Bearer $token" https://api.github.com/user | jq -r .login 2>/dev/null)
              if [ "$USER_LOGIN" != "null" ] && [ "$USER_LOGIN" != "" ]; then
                echo "$name belongs to: $USER_LOGIN"
              else
                echo "$name: Not a valid GitHub PAT or expired."
              fi
            fi
          }

          check_token "ARGON_GITHUB_TOKEN" "${{ secrets.ARGON_GITHUB_TOKEN }}"
          
