name: testing for PR

on:
  pull_request:

jobs:
  build:
    name: testing PR build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          stable: "false"
          go-version: "1.18"
      - run: go version

      - name: Configure git url
        run: |
          git config --global url.https://${{ secrets.ARGON_GH_TOKEN }}@github.com/.insteadOf https://github.com/
      - name: Run tests
        env:
          GOPRIVATE: github.com/argonsecurity/*
        run: make test
      - name: Remove git url
        run: |
          git config --global url.https://github.com/.insteadOf https://${{ secrets.ARGON_GH_TOKEN }}@github.com/
