name: testing for PR

on:
  pull_request:

jobs:
  build:
    name: testing PR build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.18'
      - run: go version

      - name: Run tests
        run: make test
