name: go-git-pr-commenter release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: releasing go-git-pr-commenter
    runs-on: arc-runner-set

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.18'
      - run: go version

      - name: Configure git url
        run: |
          git config --global url.https://${{ secrets.ARGON_GH_TOKEN }}@github.com/argonsecurity/.insteadOf https://github.com/argonsecurity/
          git config --global url.https://${{ secrets.AQUASEC_COM_GH_TOKEN }}@github.com/aquasec-com/.insteadOf https://github.com/aquasec-com/

      - name: Release
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --clean # Changed from --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPRIVATE: github.com/argonsecurity/*, github.com/aquasec-com/*

      - name: Remove git url
        if: always()
        run: |
          git config --global --unset url.https://${{ secrets.ARGON_GH_TOKEN }}@github.com/argonsecurity/.insteadOf
          git config --global --unset url.https://${{ secrets.AQUASEC_COM_GH_TOKEN }}@github.com/aquasec-com/.insteadOf